plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag

remote_theme: niklasbuschmann/contrast@v2.11

title: Developers Code Hub
tagline: Blog about Software, Cloud, IoT, and Machine Learning
author: "Juan M. Carballo"

show_excerpts: true
show_sidebar: true

navigation:
  - { file: "index.markdown", title: "Home", icon: home}
  - { file: "search.html", title: "Search", url: "/search/", icon: search }
  - { file: "about.markdown", title: "About Me" }

external:
  - { title: Mail, icon: envelope, url: "mailto:jm.carb@gmail.com" }
  - { title: Github, icon: github, url: "https://github.com/jmanuelc87" }
  - { title: Twitter, icon: twitter, url: "https://twitter.com/jmanuelc87" }
